name = "snake_gtkada"
description = "Snake Game (GtkAda)"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "GPL-3.0-or-later"
website = ""
tags = ["snake", "game", "gtkada"]

executables = ["../bin/snake"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
gtkada = "^25.0.1"
